name: GitHub-Jira-Sync

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - review_requested
      - review_request_removed
      - review_submitted
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Jira ID from title depending on event type
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            TITLE="${{ github.event.issue.title }}"
          else
            TITLE="${{ github.event.pull_request.title }}"
          fi

          echo "Ti
