name: GitHub-Jira-Sync

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - review_requested
      - review_request_removed
      - review_submitted
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Jira ID from title depending on event type
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            TITLE="${{ github.event.issue.title }}"
          else
            TITLE="${{ github.event.pull_request.title }}"
          fi

          echo "Title to parse: $TITLE"

          JIRA_ID=$(echo "$TITLE" | grep -oE '[A-Z]+-[0-9]+' || true)
          echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV

      - name: Sync PR updates with Jira (Formatted comment)
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          if [ -z "${{ env.JIRA_ID }}" ]; then
            echo "No Jira ID found, skipping Jira update."
            exi
