name: GitHub-Jira-Sync

on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, review_requested, review_request_removed, review_submitted]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Jira ID from PR title
      id: extract_jira
      run: |
        JIRA_ID=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
        echo "::set-output name=jira_id::$JIRA_ID"

    - name: Debug extracted Jira ID
      run: echo "Extracted Jira ID is: ${{ steps.extract_jira.outputs.jira_id }}"

    - name: Sync PR updates with Jira (Direct API using Bearer token)
      if: steps.extract_jira.outputs.jira_id != ''
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      run: |
        STATUS=${{ github.event.action }}
        COMMENT="GitHub PR #${{ github.event.number }} is $STATUS."
        JIRA_ID=${{ steps.extract_jira.outputs.jira_id }}

        echo "Syncing with Jira using ID: $JIRA_ID"

        curl -X POST "$JIRA_BASE_URL/rest/api/2/issue/$JIRA_ID/comment" \
          -H "Authorization: Bearer $JIRA_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"body":"'"$COMMENT"'"}'
