name: GitHub-Jira-Sync

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - review_requested
      - review_request_removed
      - review_submitted
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Jira ID from title depending on event type
      run: |
        echo "Event: ${{ github.event_name }}"
        if [ "${{ github.event_name }}" = "issue_comment" ]; then
          TITLE="${{ github.event.issue.title }}"
        else
          TITLE="${{ github.event.pull_request.title }}"
        fi

        echo "Title to parse: $TITLE"

        JIRA_ID=$(echo "$TITLE" | grep -oE '[A-Z]+-[0-9]+' || true)
        if [ -z "$JIRA_ID" ]; then
          echo "No Jira ID found in title."
        else
          echo "Extracted Jira ID is: $JIRA_ID"
        fi
        echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV

    - name: Sync PR updates with Jira (Direct API using Bearer token)
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        if [ -z "${{ env.JIRA_ID }}" ]; then
          echo "No Jira ID found, skipping Jira update."
          exit 0
        fi

        if [ "${{ github.event_name }}" = "issue_comment" ] || [ "${{ github.event_name }}" = "pull_request_review_comment" ]; then
          COMMENT_BODY="${{ github.event.comment.body }}"
        else
          STATUS=${{ github.event.action }}
          COMMENT_BODY="GitHub PR #${{ github.event.number }} is $STATUS."
        fi

        echo "Posting comment to Jira:"
        echo "$COMMENT_BODY"

        curl -X POST "$JIRA_BASE_URL/rest/api/2/issue/${{ env.JIRA_ID }}/comment" \
          -H "Authorization: Bearer $JIRA_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\":\"$COMMENT_BODY\"}"
