name: GitHub-Jira-Sync

on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, review_requested, review_request_removed, review_submitted]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Jira ID from PR title
      run: |
        JIRA_ID=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
        echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV
        echo "Extracted Jira ID is: $JIRA_ID"

    - name: Sync PR updates with Jira (Direct API using Bearer token)
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      run: |
        if [ -z "${{ env.JIRA_ID }}" ]; then
          echo "No Jira ID found in PR title."
          exit 1
        fi

        echo "Syncing with Jira using ID: ${{ env.JIRA_ID }}"

        STATUS=${{ github.event.action }}
        COMMENT="GitHub PR #${{ github.event.number }} is $STATUS."

        curl -X POST "$JIRA_BASE_URL/rest/api/2/issue/${{ env.JIRA_ID }}/comment" \
          -H "Authorization: Bearer $JIRA_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"body":"'"$COMMENT"'"}'
